# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"tokenize_space": "01_segment.ipynb"}

modules = ["segment.py"]

doc_url = "https://edwardjross.github.io/mlzero/"

git_url = "https://github.com/edwardjross/mlzero/tree/master/"

def custom_doc_links(name): return None
