# AUTOGENERATED! DO NOT EDIT! File to edit: 01_segment.ipynb (unless otherwise specified).

__all__ = ['tokenize_space']

# Cell
from typing import List

# Cell
def tokenize_space(text: str) -> List[str]:
    return text.split(' ')